[package]
name = "prime-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
rayon = "1.6"
serde = "1.0"
serde_json = "1.0"


